### ISSUE TITLE
make service message readed in order

### ISSUE THREAD

**Issue by Supercip971** [Supercip971/WingOS_x64#2]

**Comment by tacticalyash** [comment]
@Supercip971 sir i want to build text editor for running the cpp code,HOW CAN I ADD TERMINAL (like VSCODE) and am looking to build for linux and windows via QT creator ,PLS SUGGEST me what i hv to do,reply me sir here

**Comment by sleepy-monax** [comment]
Hi @tacticalyash, you should open another issues, this message has nothing to do with the subject discuss here.

**Comment by Supercip971** [comment]
@tacticalyash you build it with make and you have to build the toolchain

**Comment by tacticalyash** [comment]
@Supercip971 thank you sir

**Comment by Supercip971** [comment]
you can see Build_guide.md file for building the system

**Comment by tacticalyash** [comment]
okay i shall see it
