### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by cristeigabriel** [Supercip971/WingOS_x64#4]
Hello there, I'm looking towards contributing, but, there's an issue, there's no set standards, and I think it would benefit everyone if there was a clang format config, as it is the usual standard tool for formatting.

**Comment by cristeigabriel** [comment]
Sorry, just noticed there's one, but I looked through the code and it semt like it wasn't applied.

**Comment by Supercip971** [comment]
normally it is applied, I believe the time_service file was not up to date, I fixed this in the last commit : 
https://github.com/Supercip971/WingOS_x64/commit/dcccdf72adb8c8ec66bada9ed2ced8437a3fdea4
